; DeskFlow aquarium controller
; Default board: ESP8266 NodeMCU (your COM3 device).

[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
lib_deps =
  bblanchon/ArduinoJson @ ^7.2.1
build_flags =
  -DDESKFLOW_LIGHT_PIN=2
  -DDESKFLOW_FILTER_PIN=4

; Optional later: real ESP32 board
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.2.1
build_flags =
  -DDESKFLOW_LIGHT_PIN=25
  -DDESKFLOW_FILTER_PIN=26
  -DCORE_DEBUG_LEVEL=0
